environment.property-sources=branding,ocr,kavosh

spring.application.name=PAM

database.db-name=pam

docker.mount-path=${MOUNT_PATH:/lib/appdata/pam}
docker.hr-disk-root-path=${docker.mount-path}/records
docker.jar-file=/pam.jar

security.session-management-mode=JDBC
security.des.controllers-packages=ir.fidar.pam.controller
security.des.entities-packages=ir.fidar.pam.domain.model

branding.favicon-path=/branding/favicon.png
branding.system-icon-path=/branding/logo.jpeg

converter.ip-address=172.20.1.20
converter.port=8080

remote-session-input-extraction.max-pool-size=4
remote-session-input-extraction.thread-name-prefix=remote-session-input-extraction

remote-session.kavosh-response-wait-time=10